/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "data.h"


void
vehiculereservationservice_1(char *host)
{
	CLIENT *clnt;
	struct Results  *result_1;
	struct tipo_veicolo  show_reservations_1_arg;
	int  *result_2;
	struct patenti  update_license_1_arg;

	strcpy(show_reservations_1_arg.tipo, "camper");
	strcpy(update_license_1_arg.numeroTarga, "AN745NL");
	strcpy(update_license_1_arg.nuovaPatente, "01234");

#ifndef	DEBUG
	clnt = clnt_create (host, VehiculeReservationService, V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = show_reservations_1(&show_reservations_1_arg, clnt);
	if (result_1 == (struct Results *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = update_license_1(&update_license_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	for (int i=0; i<6; i++){
		printf("%s %s\n", result_1->reservations[i].plate_number, result_1->reservations[i].license_number);
	}

	printf("%d\n", *result_2);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	vehiculereservationservice_1 (host);
exit (0);
}
