/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "data.h"
#define LIBERO "L"
#define MAX_PRENOTAZIONI 10

char prenotazioni[MAX_PRENOTAZIONI][1000][1000];
int initlialized = 0;


void initialize(){
	// Inizializzazione per i test
    strcpy(prenotazioni[0][0], "AN745NL");
    strcpy(prenotazioni[0][1], "00003");
    strcpy(prenotazioni[0][2], "auto");
    strcpy(prenotazioni[0][3], "AN745NL_img");

    strcpy(prenotazioni[1][0], "FE457GF");
    strcpy(prenotazioni[1][1], "50006");
    strcpy(prenotazioni[1][2], "camper");
    strcpy(prenotazioni[1][3], "FE457GF_img");

    strcpy(prenotazioni[2][0], LIBERO);
    strcpy(prenotazioni[2][1], "0");
    strcpy(prenotazioni[2][2], LIBERO);
    strcpy(prenotazioni[2][3], LIBERO);

    strcpy(prenotazioni[3][0], LIBERO);
    strcpy(prenotazioni[3][1], "0");
    strcpy(prenotazioni[3][2], LIBERO);
    strcpy(prenotazioni[3][3], LIBERO);

    strcpy(prenotazioni[4][0], "NU547PL");
    strcpy(prenotazioni[4][1], "40063");
    strcpy(prenotazioni[4][2], "auto");
    strcpy(prenotazioni[4][3], "NU547PL_img");

    strcpy(prenotazioni[5][0], "LR897AH");
    strcpy(prenotazioni[5][1], "56832");
    strcpy(prenotazioni[5][2], "camper");
    strcpy(prenotazioni[5][3], "LR897AH_img");

    strcpy(prenotazioni[6][0], "MD506DW");
    strcpy(prenotazioni[6][1], "00100");
    strcpy(prenotazioni[6][2], "camper");
    strcpy(prenotazioni[6][3], "MD506DW_img");
}

struct Results *
show_reservations_1_svc(struct tipo_veicolo *argp, struct svc_req *rqstp)
{
	static struct Results  result;
	int foundResults = 0;

	if (initlialized == 0){
		initialize();
		initlialized = 1;
	}

	// Trovare i veicoli di tipo richiesto immatricolati dopo il 2011
	for (int i=0; i<MAX_PRENOTAZIONI; i++){
		if (strcmp(prenotazioni[i][2], argp->tipo) == 0 && (prenotazioni[i][0][0]>'E' || (prenotazioni[i][0][0]=='E' && prenotazioni[i][0][1]>'D'))){
			strcpy(result.reservations[foundResults].plate_number, prenotazioni[i][0]);
			strcpy(result.reservations[foundResults].license_number, prenotazioni[i][1]);

			foundResults++;
			if (foundResults == 6) break;
		}
	}

	return &result;
}

int *
update_license_1_svc(struct patenti *argp, struct svc_req *rqstp)
{
	static int  result;
	
	// Nel caso in cui non trovi la coppia patente targa, errore
	result = -1;

	if (initlialized == 0){
		initialize();
		initlialized = 1;
	}

	// Trovo numero di patente e targa
	for (int i=0; i<MAX_PRENOTAZIONI; i++){
		if (strcmp(prenotazioni[i][0], argp->numeroTarga) == 0){

			strcpy(prenotazioni[i][1], argp->nuovaPatente);
			result = 0;
			break;
		}
	}

	return &result;
}
